config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#anasayfa'

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :articles,  path: 'blog'
  end

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :galeris,  path: 'galeri'
  end

  get 'iletisim', to: 'iletisim#index'

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :duyurulars,  path: 'duyurular'
  end

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :yonetims,  path: 'yönetim'
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, Article, user_id: user.id
      can :read, :all
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum:1, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 300 }

  belongs_to :user
end

app/models/duyurular.rb
class Duyurular < ApplicationRecord
end

app/models/galeri.rb
class Galeri < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  serialize :avatars, JSON
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/models/yonetim.rb
class Yonetim < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller? # for add name of people to the Users.name

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all.reverse
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def show
    #@articles = @user.articles.paginate(page: params[:page])
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      #flash[:notice] = "Article was successfully created"
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article '#{@article.title}' was successfully deleted"

    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, :user_id)
    end
end

app/controllers/duyurulars_controller.rb
class DuyurularsController < ApplicationController

  load_and_authorize_resource

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_duyurular, only: [:edit, :update, :show, :destroy]

  def index
    @duyurulars = Duyurular.all.reverse
  end

  def new
    @duyurular = Duyurular.new
  end

  def edit
  end

  def show
  end

  def create
    @duyurular = Duyurular.new(duyurular_params)
    @duyurular.user_id = current_user.id
    if @duyurular.save
      redirect_to @duyurular
    else
      render action: 'new'
    end
  end

  def update
    if @duyurular.update(duyurular_params)

      redirect_to @duyurular
    else
      render action: 'edit'
    end
  end

  def destroy
    @duyurular.destroy

    redirect_to duyurulars_path
  end

  private
    def set_duyurular
      @duyurular = Duyurular.find(params[:id])
    end

    def duyurular_params
      params.require(:duyurular).permit(:title, :text, :user_id)
    end

end

app/controllers/galeris_controller.rb
class GalerisController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_galeri, only: [:show, :edit, :update, :destroy]

  def index
    @galeris = Galeri.all.sort
  end

  def show
  end

  def new
    @galeri = Galeri.new
  end

  def edit
  end

  def create
    @galeri = Galeri.new(galeri_params)
    if @galeri.save
      redirect_to @galeri, notice: 'Photo was successfully created.'
    else
      render :new
    end
  end

  def update
    if @galeri.update(galeri_params)
      redirect_to @galeri, notice: 'Photo was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @galeri.destroy
    redirect_to galeris_url, notice: 'Photo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galeri
      @galeri = Galeri.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galeri_params
      params.require(:galeri).permit(:title, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/iletisim_controller.rb
class IletisimController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def hakkimizda
  end

end

app/controllers/yonetims_controller.rb
class YonetimsController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_yonetim, only: [:edit, :update, :show, :destroy]

  def index
    @yonetims = Yonetim.all.sort
  end

  def new
    @yonetim = Yonetim.new
  end

  def edit
  end

  def show
  end

  def create
    @yonetim = Yonetim.new(yonetim_params)
    @yonetim.user_id = current_user.id
    if @yonetim.save
      redirect_to @yonetim
    else
      render action: 'new'
    end
  end

  def update
    if @yonetim.update(yonetim_params)
      redirect_to @yonetim
    else
      render action: 'edit'
    end
  end

  def destroy
    @yonetim.destroy
    redirect_to yonetims_path
  end

  private
    def set_yonetim
      @yonetim = Yonetim.find(params[:id])
    end

    def yonetim_params
      params.require(:yonetim).permit(:ny, :title_y, :text_y, :nu, :title_u, :text_u, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/duyurular_helper.rb
module DuyurularHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iletisim_helper.rb
module IletisimHelper
end

app/helpers/yonetims_helper.rb
module YonetimsHelper
end

app/views/articles/_form.html.erb
<% provide(:title, 'Blog') %>
<% if @article.errors.any? %>
<h2><%= pluralize(@article.errors.count, "error") %> prohibited this post from being saved:</h2>
<ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for(@article) do |f| %>

    <p>
        <%= f.label :title, "Duyurular" %><br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description, "Aciklamalar" %><br>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit class: "btn btn-primary", type: "submit", value: "Tamam", data: { disable_with: "Yükleniyor..."} %>
    </p>

<% end %>

<%= link_to "Dönmek hepsi blog sayfa", articles_path, class: "btn btn-primary btn-xs" %>

app/views/articles/edit.html.erb
<% provide(:title, 'Blog') %>
<div class="container">
  <div class="row">

<h2>Blog yazısını değiştir</h2>

<%= render 'form', post: @article %>

    </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, 'Blog') %>

<div class="container">
  <div class="row">

<h2>Bütün bloglar</h2><br>

<% @articles.each do |article| %>

    <p><span><%= article.title %></span></p>

    <p><%= article.description %></p>

    <p class="user"><%= article.user.name %></p>

    <p class="date"><%= l(article.created_at, format: :long) %></p>

    <p>
        <%= link_to 'Gösteri', article_path(article), class: "btn btn-info btn-xs" %>

        <% if can? :update, article %>
        <%= link_to 'Değiştir', edit_article_path(article), class: "btn btn-warning btn-xs" %>
        <% end %>

        <% if can? :destroy, article %>
        <%= link_to 'Sil', article_path(article), method: :delete, data: {confirm: 'Emin misin ?'}, class: "btn btn-danger btn-xs" %>
        <% end %>
    </p>

    <hr>

<% end %>

<%= link_to 'Yeni blog', new_article_path(@article), class: "btn btn-success btn-lg" %>

    </div>
</div>
<br>

app/views/articles/new.html.erb
<% provide(:title, 'Blog') %>
<%= tag.div class: 'container' do %>
  <%= tag.div class: 'row' %>

<h2>Yeni blog yapabilirsin</h2>

<%= render 'form' %>

<% end %>

app/views/articles/show.html.erb
<% provide(:title, 'Blog') %>
<div class="container">
  <div class="row">

<p><span><%= @article.title %></span></p>
<p><%= @article.description %></p>

<% if can? :update, @article %>
<%= link_to "Değistir", edit_article_path(@article), class: "btn btn-warning btn-xs" %>
<% end %>

<%= link_to "Blog sayfasına dön", articles_path, class: "btn btn-primary btn-xs" %>
    </div>
</div>

app/views/duyurulars/_form.html.erb
 <script>
  $( function() {
    $( "#datepicker" ).datepicker({
        dateFormat:'d/m/yy'
    });

    });
  </script>



<% provide(:title, 'Duyurular') %>
<% if @duyurular.errors.any? %>
<h2><%= pluralize(@duyurular.errors.count, "error") %> prohibited this post from being saved:</h2>
<ul>
    <% @duyurular.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for(@duyurular) do |f| %>

    <p>
        <%= f.label :title, "Tarih" %><br>
        <%= f.text_field :title, id:"datepicker" %>
    </p>

    <p>
        <%= f.label :text, "Aciklamalar" %><br>
        <%= f.text_area :text, id: "datepicker" %>
    </p>

    <p>
        <%= f.submit class: "btn btn-primary", type: "submit", value: "Tamam", data: { disable_with: "Yükleniyor..."} %>
    </p>

<% end %>

<%= link_to "Dönmek hepsi blog sayfa", duyurulars_path, class: "btn btn-primary btn-xs" %>

app/views/duyurulars/edit.html.erb
<% provide(:title, 'Duyurular') %>
<div class="container">
  <div class="row">

<h2>Duyurular yazısını değiştir</h2>

<%= render 'form' %>

    </div>
</div>

app/views/duyurulars/index.html.erb
<% provide(:title, 'Duyurular') %>
<div class="container">
  <div class="row">

<h2> Bütün duyurular</h2><br>

<% @duyurulars.each do |duyurular| %>

    <span><%= duyurular.title %></span>

    <p><%= duyurular.text %></p>

    <p class="date"><%= l(duyurular.created_at, format: :long) %></p>

    <p>
        <%= link_to 'Gösteri', duyurular_path(duyurular), class: "btn btn-info btn-xs" %>

        <% if can? :update, duyurular %>
        <%= link_to 'Değiştir', edit_duyurular_path(duyurular), class: "btn btn-warning btn-xs" %>
        <% end %>

        <% if can? :destroy, duyurular %>
        <%= link_to 'Sil', duyurular_path(duyurular), method: :delete, data: {confirm: 'Emin misin ?'}, class: "btn btn-danger btn-xs" %>
        <% end %>
    </p>

    <hr>

<% end %>

<% if can? :create, :duyurular %>
  <%= link_to 'Yeni duyurular', new_duyurular_path(@duyurular), class: "btn btn-success btn-lg" %>
<% end %>

    </div>
</div>
<br>

  </<div>
</div>

app/views/duyurulars/new.html.erb
<% provide(:title, 'Duyurular') %>
<div class="container">
  <div class="row">

<h2>Yeni duyurular yapabilirsin</h2>

<%= render 'form' %>

  </div>
</div>

app/views/duyurulars/show.html.erb
<% provide(:title, 'Duyurular') %>
<div class="container">
  <div class="row">

<span><%= @duyurular.title %></span>

<p><%= @duyurular.text %></p>

<p class="date"><%= l(@duyurular.created_at, format: :long) %></p>

<% if can? :update, @duyurular %>
<%= link_to "Değistir", edit_duyurular_path(@duyurular), class: "btn btn-warning btn-xs" %>
<% end %>

<%= link_to "Duyurular sayfasına dön", duyurulars_path, class: "btn btn-primary btn-xs" %>
    </div>
</div>

app/views/galeris/_form.html.erb
<% provide(:title, 'Galeri') %>
<%= form_for(@galeri,:html => {:multipart => true}) do |form| %>

  <div class="field">
    <%= form.label :title, "Fotograf adı" %><br>
    <%= form.text_field :title, id: :galeri_title %>
  </div><br>

  <div class="field">
    <%= form.label :avatar, "Fotograf seç" %>
    <%= form.file_field :avatar %>
  </div><br>

  <div class="actions">
    <%= form.submit class: "btn btn-primary", type: "submit", value: "Tamam", data: { disable_with: "Yükleniyor..."} %>
  </div>

<% end %>

app/views/galeris/edit.html.erb
<% provide(:title, 'Galeri') %>
<div class="container">
  <div class="row">

<h2>Fotograf değiştir</h2>

<%= render 'form', post: @galeri %>

<br>
<%= link_to 'Göster', @galeri, class: "btn btn-info btn-xs" %>
<%= link_to 'Geri', galeri_path, class: "btn btn-primary btn-xs" %>

    </div>
</div>

app/views/galeris/index.html.erb
<% provide(:title, 'Galeri') %>
<div class="container">
  <div class="row">

    <h2>Galeri</h2><br>
    <% @galeris.each do |g| %>
      <div class="col-md-4">
        <a href="<%= galeri_path(g.id) %>">
          <%= image_tag g.avatar.medium.url(g.avatar_index), class: "galeri" %>
        </a><br>
        <%= g.title %><br>
        <% if can? :update, @galeri %>
        <%= link_to 'Değiştir', edit_galeri_path(g), class: "btn btn-warning btn-xs" %>
        <% end %>

        <% if can? :destroy, g %>
        <%= link_to 'Sil', g, method: :delete, data: { confirm: 'Emin misin?' }, class: "btn btn-danger btn-xs" %>
        <% end %>

      </div>
    <% end %>

    <% if can? :create, @galeri %>
    <%= link_to 'Yeni foto', new_galeri_path(@galeri), class: "btn btn-success btn-lg" %>
    <% end %>
  </div>
</div>
<br>

app/views/galeris/new.html.erb
<% provide(:title, 'Galeri') %>
<div class="container">
  <div class="row">

    <h2>Yeni fotograf yükle</h2>

    <%= render 'form', post: @galeri %>

    <%= link_to 'Geri', galeris_path, class: "btn btn-primary btn-xs" %>

    </div>
</div>

app/views/galeris/show.html.erb
<% provide(:title, 'Galeri') %>
<div class="container">
  <div class="row">
<p>
  <strong>Fotograf adı:</strong>
  <%= @galeri.title %>
</p>
<%= image_tag(@galeri.avatar.thumb.url) if @galeri.avatar? %>

<% if can? :update, Galeri %>
<%= link_to 'Değiştir', edit_galeri_path(@galeri), class: "btn btn-warning btn-xs" %>
<% end %>

<%= link_to 'Geri', galeris_path, class: "btn btn-primary btn-xs" %>
  </div>
</div>

app/views/iletisim/index.html.erb
<% provide(:title, 'İletişim') %>
<div id="cont" class="container">
    <div class="row">
      <div class="col-sm-12">
        <p><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i> +90 538 471 52 52</p>

        <p><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i> aslancami@aslancamikoyudernegi.com.tr</p>

        <p><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i> Dumlupınar mah Ordu sok №19 Pendik/Istanbul</p>

      </div>
  </div>
</div>

app/views/welcome/anasayfa.html.erb
<%= render 'layouts/slider' %>

<div class="container">
  <div class="row">
    <div id="baskan" class="col-sm-4">
      <div class="thumbnail">
      <%= image_tag("boss.jpg", class: "img-responsive center-block", alt: "baskan", id: "boss") %>

        <div id="name" class="caption">
            Başkan <br> Nihat Coşkun
        </div>
      </div>
    </div>

    <div id="merhaba" class="col-sm-8">
      <p>Merhaba</p>
        <br>
        <p>Derneğimiz 2015 yılında Aslancamii köyü ve mahallelerinden dernekleşmenin önemini bilen hizmet gönüllüleri tarafından kurulmuştur.
        Derneğimiz ilke olarak yardımlaşma ve dayanışmayı görev bilmiştir.
        Dernek yönetim kurulu, üyeleri ve aileleri derneğimizin gelişiminde önemli katkıları olmuştur.
        Derneğimiz sosyal bir dernek olarak büyümeye devam edecektir.
        Saygılarımla.</p>
        <br>
        <p>Herşey Aslancami için</p>
      </p>
      <br>
    </div>
  </div>
</div>

app/views/yonetims/_form.html.erb
<% provide(:title, 'Yönetim ve üyeleri') %>
<% if @yonetim.errors.any? %>
<h2><%= pluralize(@yonetim.errors.count, "error") %> prohibited this post from being saved:</h2>
<ul>
    <% @yonetim.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for(@yonetim) do |f| %>


    <p>
        <%= f.label :title_y, "Kurucu yönetim" %><br>
        <%= f.text_field :title_y %>
    </p>

    <p>
        <%= f.label :title_u, "Yönetim kurulu" %><br>
        <%= f.text_field :title_u %>
    </p>

    <p>
        <%= f.submit class: "btn btn-primary", type: "submit", value: "Tamam", data: { disable_with: "Yükleniyor..."} %>
    </p>

<% end %>

<%= link_to "Dönmek hepsi blog sayfa", yonetims_path, class: "btn btn-primary btn-xs" %>

app/views/yonetims/_upddel.html.erb
<% @yonetims.each do |yonetim| %>
    <% if can? :update, yonetim %>
        <%= link_to 'Değiştir', edit_yonetim_path(yonetim), class: "btn btn-warning btn-xs" %>
    <% end %>

    <% if can? :destroy, yonetim %>
        <%= link_to 'Sil', yonetim_path(yonetim), method: :delete, data: {confirm: 'Emin misin ?'}, class: "btn btn-danger btn-xs" %>
    <% end %>

<% end %>

app/views/yonetims/edit.html.erb
<% provide(:title, 'Yönetim ve üyeleri') %>
<div class="container">
  <div class="row">

<h2>Yonetim yazısını değiştir</h2>

<%= render 'form' %>

    </div>
</div>

app/views/yonetims/index.html.erb
<% provide(:title, 'Yönetim ve üyeleri') %>

<div class="container">
    <h2>Anadolu yakası aslancami derneği yönetim ve üyeleri</h2><br>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Kurucu yönetim</th>
        <th>Yönetim kurulu</th>
      </tr>
    </thead>

    <tbody>
        <% @yonetims.each do |yonetim| %>
          <tr>

            <td><%= yonetim.title_y %>
                <% if can? :update, yonetim %>
                  <%= link_to 'Değiştir', edit_yonetim_path(yonetim), class: "btn btn-warning btn-xs" %>
                <% end %>

                <% if can? :destroy, yonetim %>
                 <%= link_to 'Sil', yonetim_path(yonetim), method: :delete, data: {confirm: 'Emin misin ?'}, class: "btn btn-danger btn-xs" %>
                <% end %>
            </td>


            <td><%= yonetim.title_u %>
                <% if can? :update, yonetim %>
                  <%= link_to 'Değiştir', edit_yonetim_path(yonetim), class: "btn btn-warning btn-xs" %>
                <% end %>

                <% if can? :destroy, yonetim %>
                  <%= link_to 'Sil', yonetim_path(yonetim), method: :delete, data: {confirm: 'Emin misin ?'}, class: "btn btn-danger btn-xs" %>
                <% end %>
            </td>
          </tr>
        <% end %>
    </tbody>
</table>
</div>

<% if can? :create, :yonetim %>
  <%= link_to 'Yeni', new_yonetim_path(@yonetim), class: "btn btn-success btn-lg" %>
<% end %>

</div>

app/views/yonetims/new.html.erb
<% provide(:title, 'Yönetim ve üyeleri') %>
<div class="container">
  <div class="row">

<h2>Yeni yonetim yapabilirsin</h2>

<%= render 'form' %>

  </div>
</div>

app/views/yonetims/show.html.erb
<% provide(:title, 'Yönetim ve üyeleri') %>
<div class="container">
  <div class="row">

<p><%= @yonetim.title_y %></p>

<p><%= @yonetim.title_u %></p>

<p class="date"><%= l(@yonetim.created_at, format: :long) %></p>

<% if can? :update, @yonetim %>
<%= link_to "Değistir", edit_yonetim_path(@yonetim), class: "btn btn-warning btn-xs" %>
<% end %>

<%= link_to "Yonetim sayfasına dön", yonetims_path, class: "btn btn-primary btn-xs" %>
    </div>
</div>