config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#anasayfa'

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :articles,  path: 'blog'
  end

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :galeris,  path: 'galeri'
  end

  get 'iletisim', to: 'iletisim#index'

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :duyurulars,  path: 'duyurular'
  end

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :yonetims,  path: 'yönetim'
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, Article, user_id: user.id
      can :read, :all
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum:1, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 300 }

  belongs_to :user
end

app/models/duyurular.rb
class Duyurular < ApplicationRecord
end

app/models/galeri.rb
class Galeri < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  serialize :avatars, JSON
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/models/yonetim.rb
class Yonetim < ApplicationRecord
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all.reverse
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def show
    #@articles = @user.articles.paginate(page: params[:page])
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      #flash[:notice] = "Article was successfully created"
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article '#{@article.title}' was successfully deleted"

    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, :user_id)
    end
end

app/controllers/duyurulars_controller.rb
class DuyurularsController < ApplicationController

  load_and_authorize_resource

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_duyurular, only: [:edit, :update, :show, :destroy]

  def index
    @duyurulars = Duyurular.all.reverse
  end

  def new
    @duyurular = Duyurular.new
  end

  def edit
  end

  def show
  end

  def create
    @duyurular = Duyurular.new(duyurular_params)
    @duyurular.user_id = current_user.id
    if @duyurular.save
      redirect_to @duyurular
    else
      render action: 'new'
    end
  end

  def update
    if @duyurular.update(duyurular_params)

      redirect_to @duyurular
    else
      render action: 'edit'
    end
  end

  def destroy
    @duyurular.destroy

    redirect_to duyurulars_path
  end

  private
    def set_duyurular
      @duyurular = Duyurular.find(params[:id])
    end

    def duyurular_params
      params.require(:duyurular).permit(:title, :text, :user_id)
    end

end

app/controllers/galeris_controller.rb
class GalerisController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_galeri, only: [:show, :edit, :update, :destroy]

  def index
    @galeris = Galeri.all.sort
  end

  def show
  end

  def new
    @galeri = Galeri.new
  end

  def edit
  end

  def create
    @galeri = Galeri.new(galeri_params)
    if @galeri.save
      redirect_to @galeri, notice: 'Photo was successfully created.'
    else
      render :new
    end
  end

  def update
    if @galeri.update(galeri_params)
      redirect_to @galeri, notice: 'Photo was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @galeri.destroy
    redirect_to galeris_url, notice: 'Photo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galeri
      @galeri = Galeri.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galeri_params
      params.require(:galeri).permit(:title, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/iletisim_controller.rb
class IletisimController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def hakkimizda
  end

end

app/controllers/yonetims_controller.rb
class YonetimsController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_yonetim, only: [:edit, :update, :show, :destroy]

  def index
    @yonetims = Yonetim.all.sort
  end

  def new
    @yonetim = Yonetim.new
  end

  def edit
  end

  def show
  end

  def create
    @yonetim = Yonetim.new(yonetim_params)
    @yonetim.user_id = current_user.id
    if @yonetim.save
      redirect_to @yonetim
    else
      render action: 'new'
    end
  end

  def update
    if @yonetim.update(yonetim_params)
      redirect_to @yonetim
    else
      render action: 'edit'
    end
  end

  def destroy
    @yonetim.destroy
    redirect_to yonetims_path
  end

  private
    def set_yonetim
      @yonetim = Yonetim.find(params[:id])
    end

    def yonetim_params
      params.require(:yonetim).permit(:ny, :title_y, :text_y, :nu, :title_u, :text_u, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/duyurular_helper.rb
module DuyurularHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iletisim_helper.rb
module IletisimHelper
end

app/helpers/yonetims_helper.rb
module YonetimsHelper
end

app/views/layouts/_favicon.html.erb
<% %w(57 60 72 76 114 120 144 152).each do |size| %>
  <%= favicon_link_tag "fav/apple-touch-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

app/views/layouts/_footer.html.erb
<!--Footer-->
<br>
<div id="footer3" class="container-fluid">
  <br>
  <div id="footer4" class="container">
    <div class="row">
      <div class="col-xs-6 col-sm-3">
        <a href='http://www.fatsa.gov.tr/' target="_blank", alt="fatsagov">
          <%= image_tag("icon/1.png", size: "100") %>
        </a>
      </div>

       <div class="col-xs-6 col-sm-3">
        <a href='http://www.fatsa.bel.tr/' target="_blank", alt="fatsagov">
          <%= image_tag("icon/2.png", size: "100") %>
        </a>
      </div>

       <div class="col-xs-6 col-sm-3">
        <a href='http://www.ordu.bel.tr/' target="_blank", alt="fatsagov">
          <%= image_tag("icon/3.png", size: "100") %>
        </a>
      </div>

       <div class="col-xs-6 col-sm-3">
        <a href='http://www.ordu.gov.tr/' target="_blank", alt="fatsagov">
          <%= image_tag("icon/4.png", size: "100") %>
        </a>
      </div>
    </div>
  </div>
  <br>
  <br>
</div>


<div id="footer" class="container-fluid">
  <div id="footer2" class="container">
    <div class="row">
      <div class="col-sm-6 col-md-6">
        <p><a href="tel:+905384715252" id="telefon" class="sog"><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i> +90 538 471 52 52</a></p>

        <p><a href="mailto:aslancami@aslancamikoyudernegi.com.tr" id="email"><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i> aslancami@aslancamikoyudernegi.com.tr</a></p>

        <p><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i> Dumlupınar mah Ordu sok №19 Pendik/Istanbul</p>
        <br>

      </div>



      <div id="p" class="col-sm-6 col-md-6">


        <a href='https://www.facebook.com/groups/961187180582440/?fref=nf' target="_blank", alt="f">
          <%= image_tag("soz/f.png") %>
        </a>

        <a href='https://www.twitter.com' target="_blank", alt="t">
          <%= image_tag("soz/t.png") %>
        </a>

        <a href='https://www.youtube.com' target="_blank", alt="u">
          <%= image_tag("soz/u.png") %>
        </a>

      </div>

    </div>
  </div>
</div>

<div id="avtor" class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <p><a href="mailto:ovin999@gmail.com"></i>Made by Olga Coşkun</a></p>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/_logo.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-2">
        <%= link_to(image_tag("logo150.png", class: "img-responsive center-block", alt: "Responsive image", id: "logo"), root_path) %>
    </div>

    <div class="col-sm-10">
      <h1>Ordu Fatsa Anadolu Yakası Aslancami Köyü Derneği</h1>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<!--Navbar-->
<nav class="navbar">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><%= link_to "", root_path, class: "fa fa-home", id: "icon" %></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Hakkımızda <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Derneğimizin Tarihçesi</a></li>
          <li><a href="#">Derneğimizin Tüzüğü</a></li>
          <li><a href="#">Derneğimizin Etkinlikleri</a></li>
        </ul>
      </li>

      <li><%= link_to "yönetim ve üyeleri", yonetims_path %></li>
      <li><%= link_to "galeri", galeris_path %></li>
      <li><%= link_to "iletişim", iletisim_path %></li>
      <li><%= link_to "duyurular", duyurulars_path %></li>
      <li><%= link_to "blog", articles_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to " Üye ol", new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
      <li><% if user_signed_in? %>
            <%= link_to "Çıkış", destroy_user_session_path, method: :delete, id: "cikis" %>
            <p id="curuser"><%= current_user.email %></p>
          <% else %>
            <%= link_to " Giriş Yap", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
          <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">

  <!-- Wrapper for slides -->
<div class="container-fluid">
  <div class="row">
    <div id="slider" class="col-sm-12">
       <div class="carousel-inner">

        <div class="item active">
          <%= image_tag("1111.jpg", alt: "", style: "width:100%") %>
        </div>

        <div class="item">
          <%= image_tag("2222.jpg", alt: "", style: "width:100%") %>
        </div>

        <div class="item">
          <%= image_tag("3333.jpg", alt: "", style: "width:100%") %>
        </div>

        <div class="item">
          <%= image_tag("4444.jpg", alt: "", style: "width:100%") %>
        </div>

        <div class="item">
          <%= image_tag("5555.jpg", alt: "", style: "width:100%") %>
        </div>



    <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>
</div>
<!--Slider end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="tr">
  <head>
    <title><%= yield(:title) %> | Aslancamikoyudernegi</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <script src="https://use.fontawesome.com/1af24c5af0.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <%= favicon_link_tag 'fav/fav.ico' %>
    <%= favicon_link_tag 'fav/fav.ico', rel: 'apple-touch-icon', type: 'image/png' %>

    <%= render 'layouts/favicon' %>

  </head>

  <body>
    <%= render 'layouts/navigation' %>


        <%= render 'layouts/logo' %>


    <%= yield %>

<%= render 'layouts/footer' %>

  </body>
</html>